MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './checkpoint/jx_vit_base_p16_224.pth'
  METRIC_LOSS_TYPE: 'triplet'
  ID_LOSS_TYPE: 'softmax'
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
#  STEP: 4 #16-STRIDE_SIZE
  FEAT_DIM: 768

  ICS: False

  MIXUP: True

  SIE_CAMERA: False
  SIE_VIEW: False
  SIE_COE: 3.0

  JPM: True
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  DEVIDE_LENGTH: 4

  PROMPT:
    USE: True
    NUM_TOKENS: 1
    LOCATION: "prepend"
    # prompt initalizatioin:
    # (1) default "random"
    # (2) "final-cls" use aggregated final [cls] embeddings from training dataset
    # (3) "cls-nolastl": use first 12 cls embeddings (exclude the final output) for deep prompt
    # (4) "cls-nofirstl": use last 12 cls embeddings (exclude the input to first layer)
    INITIATION: "random"  # "final-cls", "cls-first12"
    PROJECT: -1  # "projection mlp hidden dim"
    DEEP: True   # "whether do deep prompt or not, only for prepend location"
    DROPOUT_RATE: 0.0
    #According to the model has been selected(Vit-B/16)
    VIT_EMBED_DIM: 768
    VIT_DEPTH: 12
    VIT_PATCH_SIZE: 16

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market_shoes')
  ROOT_DIR: ('./data/')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 1
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005
TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: './logs/953992100843new_data.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/market_shoes/market_vit_transreid_stride_224_prompt'


